// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7p5WPldG4E_rC-K8HJDKJY7HWFuET_MI',
    appId: '1:892878474179:web:12ea9d7d900bb764a78b76',
    messagingSenderId: '892878474179',
    projectId: 'hrenb-d59dc',
    authDomain: 'hrenb-d59dc.firebaseapp.com',
    storageBucket: 'hrenb-d59dc.appspot.com',
    measurementId: 'G-D35WEPYQ7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA74RzPijC5ehMTXKi4BSAezN_0Hc5Igv8',
    appId: '1:892878474179:android:b2416f1fe978f258a78b76',
    messagingSenderId: '892878474179',
    projectId: 'hrenb-d59dc',
    storageBucket: 'hrenb-d59dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRi-ErLNOO5d2rGfGIIE9-DpikbwqFXhU',
    appId: '1:892878474179:ios:242662c049da473ca78b76',
    messagingSenderId: '892878474179',
    projectId: 'hrenb-d59dc',
    storageBucket: 'hrenb-d59dc.appspot.com',
    iosClientId: '892878474179-hr0jpd50ho65uu09g7j6la1bqhgbm0hk.apps.googleusercontent.com',
    iosBundleId: 'ru.ndevelop.hrenb.hrenb',
  );
}
